source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'
gem 'active_model_serializers'
gem 'devise_token_auth'
gem 'cancancan'
gem 'carrierwave'
gem 'mini_magick'
gem 'kaminari'
gem 'file_validators'
gem 'cancan'
gem 'haml'
gem 'haml-rails'
gem 'bower-rails'
gem 'angular-rails-templates'
gem 'omniauth-facebook'

group :development, :test do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rails-console'
  gem 'capistrano-rvm'
  gem 'capistrano-sidekiq'
  gem 'pry'
  gem 'pry-remote'
  gem 'pry-rails'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'
  gem 'rspec'
  gem 'rspec-rails'
  gem "awesome_print"
  gem 'shoulda-matchers'
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end